import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchQuote } from './quoteAPI';

const initialState = {
  text: '',
  author: '',
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(callFetchQuote())`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const callFetchQuote = createAsyncThunk(
  'quote/fetchQuote',
  async () => {
    const response = await fetchQuote();
    return await response.json();
  }
);

export const quoteSlice = createSlice({
  name: 'quote',
  initialState,
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(callFetchQuote.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(callFetchQuote.fulfilled, (state, action) => {
        state.status = 'idle';
        state.text = action.payload.content;
        state.author = action.payload.author;
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.quote)`
export const selectQuote = (state) => state.quote;

export default quoteSlice.reducer;
